# Stage 1: Base build stage
FROM python:3.12 AS builder
 
# Create the app directory
RUN mkdir /app
 
RUN apt-get update && \
    apt-get install -y gcc && \
    apt-get update && \
    apt-get install -y libmariadb-dev-compat libmariadb-dev


# Set the working directory
WORKDIR /app
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
ENV MYSQLCLIENT_CFLAGS="-I/usr/include/mysql"
ENV MYSQLCLIENT_LDFLAGS="-L/usr/lib/x86_64-linux-gnu -lmysqlclient"
 
# Upgrade pip and install dependencies
RUN pip install --upgrade pip 
 
# Copy the requirements file first (better caching)
COPY requirements.txt /app/
 
# Install Python dependencies
RUN pip install -r requirements.txt

# Verify installation path
RUN ls -l /usr/local/lib/python*.*
 
# Stage 2: Production stage
FROM python:3.12 AS final

# Set the working directory
WORKDIR /app
RUN useradd -m -r appuser && \
   #mkdir /app && \
   chown -R appuser /app
 
COPY --from=builder /usr/local/lib/python3.12/site-packages/ /usr/local/lib/python3.12/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
#COPY --from=builder /cua2024/staticfiles /app/staticfiles  
 

# Copy application code
COPY --chown=appuser:appuser . .
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
# Switch to non-root user
USER appuser
 
# Expose the application port
EXPOSE 8000 
 
# Start the application using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "cua2024.wsgi:application"]
