# Generated by Django 5.1.3 on 2024-11-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamento_funcionario',
            field=models.IntegerField(max_length=2),
        ),
    ]
