# Generated by Django 5.1.3 on 2024-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_departamento_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamento_funcionario',
            field=models.IntegerField(verbose_name=2),
        ),
    ]
