# Generated by Django 5.1.3 on 2024-11-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_departamento_funcionario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grado', models.IntegerField()),
                ('descripcion_grado', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='grado_funcionario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='funcionarios.grado'),
        ),
    ]
