# Generated by Django 5.1.3 on 2024-11-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_grado_alter_funcionario_grado_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='codigo_grado',
            field=models.IntegerField(unique=True),
        ),
    ]
