# Generated by Django 5.1.3 on 2024-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_estado_alter_funcionario_estado_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cua_funcionario',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
