# Generated by Django 5.1.3 on 2024-12-05 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_alter_funcionario_cua_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_funcionario',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('\\d{6}\\-x{1}', 'Debe ingresar un Código valido')]),
        ),
    ]
