# Generated by Django 4.2.17 on 2025-02-03 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0012_alter_funcionario_codigo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo_funcionario',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('\\d-{1}[A-Z]', 'Debe ingresar un Código valido')]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cua_funcionario',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
