# Generated by Django 4.2.17 on 2025-02-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_alter_funcionario_codigo_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cua_funcionario',
            field=models.CharField(editable=False, max_length=7, null=True, unique=True),
        ),
    ]
