# Generated by Django 4.2.17 on 2025-02-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0014_alter_funcionario_cua_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamento_funcionario',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.SET_DEFAULT, to='funcionarios.departamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_funcionario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='funcionarios.estado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='grado_funcionario',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.SET_DEFAULT, to='funcionarios.grado'),
        ),
    ]
