# Generated by Django 4.2.17 on 2025-02-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0015_alter_funcionario_departamento_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cua_funcionario',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
