# Generated by Django 4.2.17 on 2025-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0016_alter_funcionario_cua_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cua_funcionario',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
