# Generated by Django 4.2.17 on 2025-02-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0017_alter_funcionario_cua_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='grado_funcionario',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.SET_DEFAULT, to='funcionarios.grado'),
        ),
    ]
